name: ProtectionShop
version: '${project.version}'
main: d.studio.protectionshop.ProtectionShop
api-version: 1.17
depend: [NBTAPI]
authors: [ DaniCraftingYT ]
commands:
  pshop:
    description: "Tienda de protecciones"
